FROM ubuntu:22.04
RUN apt-get update && apt-get install -y python3 python3-pip
RUN python3 -m venv /opt/venv
ENV PATH=/opt/venv/bin:$PATH
COPY requirements.txt .
RUN pip3 install -r requirements.txt
COPY my_script.py /app/
WORKDIR /app
CMD ["python3", "/app/my_script.py"]